hydra:
  searchpath:
    - file://${oc.env:PWD}/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

actor_rollout_ref:
  actor:
    dpo_beta: 0.1
    checkpoint:
      contents: ${.load_contents}
    optim:
      lr_warmup_steps: 15
  rollout:
    name: sglang
    tensor_model_parallel_size: 1
    gpu_memory_utilization: 0.4
    n: 1
    val_kwargs:
      n: 1

data:
  seed: 42

reference_rollout:
  hybrid_engine: true
  model:
    path: ${actor_rollout_ref.model.path}
    tokenizer_path: ${actor_rollout_ref.model.tokenizer_path}
    trust_remote_code: ${actor_rollout_ref.model.trust_remote_code}
    use_remove_padding: ${actor_rollout_ref.model.use_remove_padding}
    enable_gradient_checkpointing: false
    use_liger: ${actor_rollout_ref.model.use_liger}
  actor: ${actor_rollout_ref.actor}
  ref: ${actor_rollout_ref.ref}
  rollout: ${actor_rollout_ref.rollout}

algorithm:
  adv_estimator: null
  dpo_beta: 0.1
  dpo_loss_type: sigmoid
  dpo_label_smoothing: 0.0
  use_kl_in_reward: false

trainer:
  log_val_generations: 0
  ref_update_freq: -1
